package com.fpt.edu.status;

public enum ValuationRequestStatus {
    REQUESTED,
    PRELIMINARY_VALUATED,
    PRODUCT_RECEIVED,
    PENDING_MANAGER_APPROVAL,
    MANAGER_APPROVED,
    PENDING_MEMBER_ACCEPTANCE,
    MEMBER_ACCEPTED,
    CANCELED
}
